In [1]:
### importing libraries and Functions

In [6]:
import pandas as pd 
import numpy as np

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

In [10]:
pip install openpyxl



     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     ------ ------------------------------ 41.0/250.0 kB 281.8 kB/s eta 0:00:01
     ------ ------------------------------ 41.0/250.0 kB 281.8 kB/s eta 0:00:01
     ---------------- ------------------- 112.6/250.0 kB 504.4 kB/s eta 0:00:01
     ---------------- ------------------- 112.6/250.0 kB 504.4 kB/s eta 0:00:01
     ---------------------------- ------- 194.6/250.0 kB 620.6 kB/s eta 0:00:01
     ---------------------------- ------- 194.6/250.0 kB 620.6 kB/s eta 0:00:01
     ---------------------------- ------- 194.6/250.0 kB 620.6 kB/s eta 0:00:01
     ---------------------------- ------- 194.6/250.0 kB 620.6 kB/s eta 0:00:01
     ---------------------------- ------- 194.6/250.0 kB 620.6 kB/s eta 0:00:01
     ---------------------------- ------- 194.6/250.0 kB 6


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
df = pd.read_excel(r"C:/Users/Raj Gupta/Downloads/a_Dataset_CreditScoring.xlsx")

In [13]:
### Data Preperation

In [14]:
df.shape ###shows count of rows and columns

(3000, 30)

In [15]:
df.head() ### shows first fewe rows of a dataset

TARGET    ID  DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
0       1   582         3           3             0         4          0.0   
1       1   662        15           9             0         3          1.0   
2       1   805         0           0             0         1          5.0   
3       1  1175         8           5             0         6          1.0   
4       1  1373         3           1             0         9          0.0   

   InqFinanceCnt24  TLTimeFirst  TLTimeLast  ...  TL50UtilCnt  TLBalHCPct  \
0                5          117          27  ...          3.0      0.9179   
1                3           14          14  ...          1.0      0.8000   
2                1          354           7  ...          5.0      0.3552   
3               10           16           4  ...          3.0      0.9127   
4                8          130          52  ...          1.0      1.2511   

   TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  TLDel60CntAll  TLOpenPct  \
0    0.2083               2             3              7     0.2083   
1    0.0000               0             0              0     1.0000   
2    0.6538               0             1              1     0.7308   
3    0.2500               1             1              1     0.7500   
4    0.0000               0             1              4     0.1429   

   TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
0              4             4       0.0000  
1             12             0       1.0000  
2              1             1       0.5263  
3              7             1       1.3333  
4              3             1       0.0000  

[5 rows x 30 columns]

In [16]:
df = df.drop("ID", axis = 1) ### dropping customer ID column fromt he dataset
df.shape

(3000, 29)

In [17]:
df.isna().sum() ###explore missing values

TARGET               0
DerogCnt             0
CollectCnt           0
BanruptcyInd         0
InqCnt06             0
InqTimeLast        188
InqFinanceCnt24      0
TLTimeFirst          0
TLTimeLast           0
TLCnt03              0
TLCnt12              0
TLCnt24              0
TLCnt                3
TLSum               40
TLMaxSum            40
TLSatCnt             4
TLDel60Cnt           0
TLBadCnt24           0
TL75UtilCnt         99
TL50UtilCnt         99
TLBalHCPct          41
TLSatPct             4
TLDel3060Cnt24       0
TLDel90Cnt24         0
TLDel60CntAll        0
TLOpenPct            3
TLBadDerogCnt        0
TLDel60Cnt24         0
TLOpen24Pct          3
dtype: int64

In [18]:
df = df.fillna(df.mean()) ###filling missing values with mean 

In [19]:
df.isna().sum() ### exploring missing values post missing values fix

TARGET             0
DerogCnt           0
CollectCnt         0
BanruptcyInd       0
InqCnt06           0
InqTimeLast        0
InqFinanceCnt24    0
TLTimeFirst        0
TLTimeLast         0
TLCnt03            0
TLCnt12            0
TLCnt24            0
TLCnt              0
TLSum              0
TLMaxSum           0
TLSatCnt           0
TLDel60Cnt         0
TLBadCnt24         0
TL75UtilCnt        0
TL50UtilCnt        0
TLBalHCPct         0
TLSatPct           0
TLDel3060Cnt24     0
TLDel90Cnt24       0
TLDel60CntAll      0
TLOpenPct          0
TLBadDerogCnt      0
TLDel60Cnt24       0
TLOpen24Pct        0
dtype: int64

In [20]:
df["TARGET"].value_counts() ### count of good loans(0) and bad loans(1)

TARGET
0    2500
1     500
Name: count, dtype: int64

In [21]:
df.groupby("TARGET").mean() ### data summary across 0 and 1

DerogCnt  CollectCnt  BanruptcyInd  InqCnt06  InqTimeLast  \
TARGET                                                              
0         1.3224      0.7664        0.1492    2.9424     3.174638   
1         1.9680      1.3100        0.1740    3.9380     2.775459   

        InqFinanceCnt24  TLTimeFirst  TLTimeLast  TLCnt03  TLCnt12  ...  \
TARGET                                                              ...   
0                3.2896      173.002      11.650   0.2844    1.832  ...   
1                4.8820      155.672      12.992   0.2280    1.768  ...   

        TL50UtilCnt  TLBalHCPct  TLSatPct  TLDel3060Cnt24  TLDel90Cnt24  \
TARGET                                                                    
0          3.986711    0.628177  0.544963          0.6044        0.6624   
1          4.533870    0.748185  0.385173          1.3340        1.5760   

        TLDel60CntAll  TLOpenPct  TLBadDerogCnt  TLDel60Cnt24  TLOpen24Pct  
TARGET                                                                      
0              2.2236   0.502376          1.180        0.8648     0.556867  
1              4.0140   0.465127          2.554        2.0860     0.600978  

[2 rows x 28 columns]

In [22]:
### Train Test Split

In [23]:
y = df.iloc[:, 0].values
x = df.iloc[:, 1:28].values

In [24]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [25]:
x

array([[ 3.    ,  3.    ,  0.    , ...,  0.2083,  4.    ,  4.    ],
       [15.    ,  9.    ,  0.    , ...,  1.    , 12.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , ...,  0.7308,  1.    ,  1.    ],
       ...,
       [ 1.    ,  1.    ,  0.    , ...,  0.4286,  1.    ,  0.    ],
       [ 4.    ,  4.    ,  0.    , ...,  0.6   ,  4.    ,  1.    ],
       [ 2.    ,  1.    ,  1.    , ...,  0.5   ,  3.    ,  2.    ]])

In [26]:
# splilliting the dataset into training and test (in ratio of 80:20)
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [27]:
### Risk Model Building
pipe = make_pipeline(StandardScaler(), LogisticRegression())

In [28]:
pipe

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [29]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [30]:
### Model Performance
pipe.score(x_test, y_test)

0.8283333333333334

In [31]:
# sc = StandardScaler()
# x_train - sc.fit_transform(x_train)
# x_test = sc.fit_transform(x_test)

In [32]:
### Risk Model Building

In [33]:
# Classifier = LogisticRegression()
# Classifier.fit(x_train, y_train)
# y_pred = Classifier.predict(x_test)

In [34]:
### Model Performance

In [35]:
# print(confusion_matrix(y_test, y_pred))

In [36]:
# print(accuracy_score(y_test, y_pred))

In [37]:
### writing output file
predictions =  pipe.predict_proba(x_test)

In [38]:
predictions

array([[0.04200938, 0.95799062],
       [0.93712307, 0.06287693],
       [0.70429866, 0.29570134],
       ...,
       [0.97248551, 0.02751449],
       [0.44309325, 0.55690675],
       [0.8677644 , 0.1322356 ]])